export { clampDimensions } from './dimensions';
export type { ImageDescriptor, ImageSource, PixelSize } from './dimensions';
export { createSolidImage, cropRawImage, paintRect } from './raw-image';
export type { PixelBox, RawImage } from './raw-image';
export { autoTrim } from './auto-trim';
export type { AutoTrimOptions } from './auto-trim';
export { sha256, pHash, hammingDistance } from './hash';
export type { PdfTextItem } from './pdf-text';
export { splitTextLayer } from './pdf-split';
export type { CropBoxSuggestion, SplitTextLayerOptions } from './pdf-split';
export { splitByProjection } from './projection-split';
export type { ProjectionSplitOptions } from './projection-split';
export { parseAnswerKeyTable, ANSWER_LETTERS } from './answer-key-parse';
export type { AnswerKeyEntry, AnswerLetter } from './answer-key-parse';
