/**
 * Hand-written stand-in for `packages/shared/src/database.types.ts`.
 *
 * The real file is generated by `pnpm db:types` against a running local
 * Supabase instance (`pnpm db:start`, which needs Docker). Neither was
 * available while this slice was written, so only the tables and RPCs this
 * slice actually calls are typed here, matching supabase/migrations exactly.
 * Regenerate and delete this file once Docker is available; every import
 * below is `import type { Database } from '@/lib/supabase/types'`, so the
 * swap is a one-line change per file (or re-export the generated type here).
 *
 * `Relationships: []` on every table is required by `@supabase/postgrest-js`'s
 * `GenericTable` constraint even though nothing here uses embedded resource
 * joins (`.select('workspaces(...)')`) — those are deliberately avoided in
 * this file in favor of two plain queries merged in application code, since
 * modeling accurate FK relationship metadata by hand isn't worth it for a
 * type file meant to be thrown away once `db:types` can run for real.
 */

type Timestamp = string;

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_path: string | null;
          locale: string;
          onboarding: Record<string, unknown>;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string };
        Update: Partial<Database['public']['Tables']['profiles']['Row']>;
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          kind: 'personal' | 'team';
          owner_id: string;
          plan_id: string;
          branding: Record<string, unknown>;
          settings: Record<string, unknown>;
          created_at: Timestamp;
          updated_at: Timestamp;
          deleted_at: Timestamp | null;
        };
        Insert: Partial<Database['public']['Tables']['workspaces']['Row']> & {
          name: string;
          slug: string;
          kind: 'personal' | 'team';
          owner_id: string;
        };
        Update: Partial<Database['public']['Tables']['workspaces']['Row']>;
        Relationships: [];
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['workspace_members']['Row']> & {
          workspace_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
        };
        Update: Partial<Database['public']['Tables']['workspace_members']['Row']>;
        Relationships: [];
      };
      workspace_invites: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          token_hash: string;
          expires_at: Timestamp;
          accepted_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['workspace_invites']['Row']> & {
          workspace_id: string;
          email: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          token_hash: string;
          expires_at: Timestamp;
        };
        Update: Partial<Database['public']['Tables']['workspace_invites']['Row']>;
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          entitlements: Record<string, unknown>;
          is_active: boolean;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['plans']['Row']> & {
          id: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['plans']['Row']>;
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          plan_id: string;
          provider: 'iyzico' | 'manual';
          provider_ref: string | null;
          status: 'trialing' | 'active' | 'past_due' | 'canceled';
          seats: number;
          current_period_end: Timestamp | null;
          cancel_at_period_end: boolean;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['subscriptions']['Row']> & {
          workspace_id: string;
          plan_id: string;
          provider: 'iyzico' | 'manual';
          status: 'trialing' | 'active' | 'past_due' | 'canceled';
        };
        Update: Partial<Database['public']['Tables']['subscriptions']['Row']>;
        Relationships: [];
      };
      usage_counters: {
        Row: {
          workspace_id: string;
          period_start: string;
          metric: string;
          value: number;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['usage_counters']['Row']> & {
          workspace_id: string;
          period_start: string;
          metric: string;
        };
        Update: Partial<Database['public']['Tables']['usage_counters']['Row']>;
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          kind: string;
          payload: Record<string, unknown>;
          status: 'pending' | 'running' | 'succeeded' | 'failed';
          run_at: Timestamp;
          attempts: number;
          last_error: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['jobs']['Row']> & { kind: string };
        Update: Partial<Database['public']['Tables']['jobs']['Row']>;
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          workspace_id: string;
          actor_id: string | null;
          action: string;
          target_type: string | null;
          target_id: string | null;
          meta: Record<string, unknown>;
          created_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['audit_log']['Row']> & {
          workspace_id: string;
          action: string;
        };
        Update: Partial<Database['public']['Tables']['audit_log']['Row']>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_entitlements: {
        Args: { p_ws: string };
        Returns: Record<string, unknown>;
      };
      increment_usage: {
        Args: { p_ws: string; p_metric: string; p_amount?: number };
        Returns: number;
      };
      is_member: {
        Args: { ws: string };
        Returns: boolean;
      };
      has_role: {
        Args: { ws: string; roles: string[] };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
