/**
 * Hand-written stand-in for `packages/shared/src/database.types.ts`.
 *
 * The real file is generated by `pnpm db:types` against a running local
 * Supabase instance (`pnpm db:start`, which needs Docker). Neither was
 * available while this slice was written, so only the tables and RPCs this
 * slice actually calls are typed here, matching supabase/migrations exactly.
 * Regenerate and delete this file once Docker is available; every import
 * below is `import type { Database } from '@/lib/supabase/types'`, so the
 * swap is a one-line change per file (or re-export the generated type here).
 *
 * `Relationships: []` on every table is required by `@supabase/postgrest-js`'s
 * `GenericTable` constraint even though nothing here uses embedded resource
 * joins (`.select('workspaces(...)')`) — those are deliberately avoided in
 * this file in favor of two plain queries merged in application code, since
 * modeling accurate FK relationship metadata by hand isn't worth it for a
 * type file meant to be thrown away once `db:types` can run for real.
 */

type Timestamp = string;

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_path: string | null;
          locale: string;
          onboarding: Record<string, unknown>;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string };
        Update: Partial<Database['public']['Tables']['profiles']['Row']>;
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          kind: 'personal' | 'team';
          owner_id: string;
          plan_id: string;
          branding: Record<string, unknown>;
          settings: Record<string, unknown>;
          created_at: Timestamp;
          updated_at: Timestamp;
          deleted_at: Timestamp | null;
        };
        Insert: Partial<Database['public']['Tables']['workspaces']['Row']> & {
          name: string;
          slug: string;
          kind: 'personal' | 'team';
          owner_id: string;
        };
        Update: Partial<Database['public']['Tables']['workspaces']['Row']>;
        Relationships: [];
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['workspace_members']['Row']> & {
          workspace_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
        };
        Update: Partial<Database['public']['Tables']['workspace_members']['Row']>;
        Relationships: [];
      };
      workspace_invites: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          token_hash: string;
          expires_at: Timestamp;
          accepted_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['workspace_invites']['Row']> & {
          workspace_id: string;
          email: string;
          role: 'owner' | 'admin' | 'editor' | 'viewer';
          token_hash: string;
          expires_at: Timestamp;
        };
        Update: Partial<Database['public']['Tables']['workspace_invites']['Row']>;
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          entitlements: Record<string, unknown>;
          is_active: boolean;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['plans']['Row']> & {
          id: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['plans']['Row']>;
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          plan_id: string;
          provider: 'iyzico' | 'manual';
          provider_ref: string | null;
          status: 'trialing' | 'active' | 'past_due' | 'canceled';
          seats: number;
          current_period_end: Timestamp | null;
          cancel_at_period_end: boolean;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['subscriptions']['Row']> & {
          workspace_id: string;
          plan_id: string;
          provider: 'iyzico' | 'manual';
          status: 'trialing' | 'active' | 'past_due' | 'canceled';
        };
        Update: Partial<Database['public']['Tables']['subscriptions']['Row']>;
        Relationships: [];
      };
      usage_counters: {
        Row: {
          workspace_id: string;
          period_start: string;
          metric: string;
          value: number;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['usage_counters']['Row']> & {
          workspace_id: string;
          period_start: string;
          metric: string;
        };
        Update: Partial<Database['public']['Tables']['usage_counters']['Row']>;
        Relationships: [];
      };
      assets: {
        Row: {
          id: string;
          workspace_id: string;
          owner_id: string | null;
          bucket: 'assets' | 'exports' | 'branding';
          path: string;
          kind: 'image' | 'thumb' | 'pdf' | 'render' | 'logo' | 'export';
          mime: string;
          bytes: number;
          width: number | null;
          height: number | null;
          sha256: string | null;
          phash: string | null;
          source:
            | 'paste'
            | 'drop'
            | 'pdf_crop'
            | 'mobile'
            | 'extension'
            | 'ai'
            | 'upload'
            | 'rich_render';
          created_at: Timestamp;
          updated_at: Timestamp;
          deleted_at: Timestamp | null;
        };
        Insert: Partial<Database['public']['Tables']['assets']['Row']> & {
          workspace_id: string;
          bucket: 'assets' | 'exports' | 'branding';
          path: string;
          kind: 'image' | 'thumb' | 'pdf' | 'render' | 'logo' | 'export';
          mime: string;
          bytes: number;
          source:
            | 'paste'
            | 'drop'
            | 'pdf_crop'
            | 'mobile'
            | 'extension'
            | 'ai'
            | 'upload'
            | 'rich_render';
        };
        Update: Partial<Database['public']['Tables']['assets']['Row']>;
        Relationships: [];
      };
      source_documents: {
        Row: {
          id: string;
          workspace_id: string;
          asset_id: string;
          name: string | null;
          page_count: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['source_documents']['Row']> & {
          workspace_id: string;
          asset_id: string;
        };
        Update: Partial<Database['public']['Tables']['source_documents']['Row']>;
        Relationships: [];
      };
      crop_sessions: {
        Row: {
          id: string;
          workspace_id: string;
          source_document_id: string;
          state: Record<string, unknown>;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['crop_sessions']['Row']> & {
          workspace_id: string;
          source_document_id: string;
        };
        Update: Partial<Database['public']['Tables']['crop_sessions']['Row']>;
        Relationships: [];
      };
      questions: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          created_by: string | null;
          kind: 'image' | 'rich';
          question_type: 'mcq' | 'tf' | 'fill' | 'match' | 'open' | 'numeric' | 'order';
          stem_asset_id: string | null;
          stem_rich: Record<string, unknown> | null;
          stem_text: string | null;
          options: unknown[];
          option_count: number | null;
          correct: unknown;
          points: number;
          difficulty: number | null;
          difficulty_observed: number | null;
          subject_id: string | null;
          topic_id: string | null;
          thumb_asset_id: string | null;
          explanation_rich: Record<string, unknown> | null;
          explanation_asset_id: string | null;
          source_meta: Record<string, unknown>;
          lang: string;
          ai_generated: boolean;
          ai_review_status: 'draft' | 'approved' | null;
          status: 'active' | 'archived';
          current_revision: number;
          created_at: Timestamp;
          updated_at: Timestamp;
          deleted_at: Timestamp | null;
        };
        Insert: Partial<Database['public']['Tables']['questions']['Row']> & {
          workspace_id: string;
          kind: 'image' | 'rich';
          question_type: 'mcq' | 'tf' | 'fill' | 'match' | 'open' | 'numeric' | 'order';
        };
        Update: Partial<Database['public']['Tables']['questions']['Row']>;
        Relationships: [];
      };
      folders: {
        Row: {
          id: string;
          workspace_id: string;
          parent_id: string | null;
          kind: 'questions' | 'tests';
          name: string;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['folders']['Row']> & {
          workspace_id: string;
          kind: 'questions' | 'tests';
          name: string;
        };
        Update: Partial<Database['public']['Tables']['folders']['Row']>;
        Relationships: [];
      };
      tags: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['tags']['Row']> & {
          workspace_id: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['tags']['Row']>;
        Relationships: [];
      };
      question_tags: {
        Row: {
          workspace_id: string;
          question_id: string;
          tag_id: string;
        };
        Insert: Database['public']['Tables']['question_tags']['Row'];
        Update: Partial<Database['public']['Tables']['question_tags']['Row']>;
        Relationships: [];
      };
      question_outcomes: {
        Row: {
          workspace_id: string;
          question_id: string;
          outcome_id: string;
        };
        Insert: Database['public']['Tables']['question_outcomes']['Row'];
        Update: Partial<Database['public']['Tables']['question_outcomes']['Row']>;
        Relationships: [];
      };
      curriculum_subjects: {
        Row: {
          id: string;
          code: string;
          name: string;
          grade_from: number | null;
          grade_to: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['curriculum_subjects']['Row']> & {
          code: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['curriculum_subjects']['Row']>;
        Relationships: [];
      };
      curriculum_topics: {
        Row: {
          id: string;
          subject_id: string;
          parent_id: string | null;
          name: string;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['curriculum_topics']['Row']> & {
          subject_id: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['curriculum_topics']['Row']>;
        Relationships: [];
      };
      curriculum_outcomes: {
        Row: {
          id: string;
          subject_id: string;
          topic_id: string | null;
          grade: number | null;
          code: string | null;
          description: string;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['curriculum_outcomes']['Row']> & {
          subject_id: string;
          description: string;
        };
        Update: Partial<Database['public']['Tables']['curriculum_outcomes']['Row']>;
        Relationships: [];
      };
      question_revisions: {
        Row: {
          id: string;
          workspace_id: string;
          question_id: string;
          revision: number;
          snapshot: Record<string, unknown>;
          created_by: string | null;
          created_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['question_revisions']['Row']> & {
          workspace_id: string;
          question_id: string;
          revision: number;
          snapshot: Record<string, unknown>;
        };
        Update: Partial<Database['public']['Tables']['question_revisions']['Row']>;
        Relationships: [];
      };
      tests: {
        Row: {
          id: string;
          workspace_id: string;
          folder_id: string | null;
          created_by: string | null;
          title: string;
          type: 'exam' | 'test_paper' | 'mock' | 'written' | 'worksheet' | 'quiz';
          status: 'draft' | 'ready' | 'archived';
          settings: Record<string, unknown>;
          settings_version: number;
          version_count: number;
          seed: number | null;
          question_count: number;
          revision: number;
          last_exported_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
          deleted_at: Timestamp | null;
        };
        Insert: Partial<Database['public']['Tables']['tests']['Row']> & {
          workspace_id: string;
          title: string;
          type: 'exam' | 'test_paper' | 'mock' | 'written' | 'worksheet' | 'quiz';
        };
        Update: Partial<Database['public']['Tables']['tests']['Row']>;
        Relationships: [];
      };
      test_items: {
        Row: {
          id: string;
          workspace_id: string;
          test_id: string;
          section_id: string | null;
          group_id: string | null;
          question_id: string;
          question_revision_id: string;
          position: string;
          points_override: number | null;
          correct_override: unknown;
          pinned: boolean;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['test_items']['Row']> & {
          workspace_id: string;
          test_id: string;
          question_id: string;
          question_revision_id: string;
          position: string;
        };
        Update: Partial<Database['public']['Tables']['test_items']['Row']>;
        Relationships: [];
      };
      students: {
        Row: {
          id: string;
          workspace_id: string;
          full_name: string;
          student_no: string | null;
          external_ref: string | null;
          archived_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['students']['Row']> & {
          workspace_id: string;
          full_name: string;
        };
        Update: Partial<Database['public']['Tables']['students']['Row']>;
        Relationships: [];
      };
      classes: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          grade: number | null;
          school_year: string | null;
          archived: boolean;
          retention_until: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['classes']['Row']> & {
          workspace_id: string;
          name: string;
        };
        Update: Partial<Database['public']['Tables']['classes']['Row']>;
        Relationships: [];
      };
      class_students: {
        Row: {
          workspace_id: string;
          class_id: string;
          student_id: string;
          created_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['class_students']['Row']> & {
          workspace_id: string;
          class_id: string;
          student_id: string;
        };
        Update: Partial<Database['public']['Tables']['class_students']['Row']>;
        Relationships: [];
      };
      online_exams: {
        Row: {
          id: string;
          workspace_id: string;
          test_id: string;
          test_snapshot_id: string | null;
          title: string;
          mode: 'async' | 'live';
          access: 'link' | 'code' | 'roster';
          join_code: string | null;
          slug: string;
          opens_at: Timestamp | null;
          closes_at: Timestamp | null;
          duration_sec: number | null;
          max_attempts: number | null;
          shuffle_questions: boolean;
          shuffle_options: boolean;
          show_results: 'never' | 'after_submit' | 'after_close';
          show_answers: boolean;
          required_fields: Record<string, unknown>;
          status: 'draft' | 'scheduled' | 'open' | 'closed';
          participant_cap: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['online_exams']['Row']> & {
          workspace_id: string;
          test_id: string;
          title: string;
          mode: 'async' | 'live';
          access: 'link' | 'code' | 'roster';
          slug: string;
        };
        Update: Partial<Database['public']['Tables']['online_exams']['Row']>;
        Relationships: [];
      };
      online_exam_items: {
        Row: {
          id: string;
          workspace_id: string;
          online_exam_id: string;
          test_item_id: string | null;
          question_id: string;
          question_revision_id: string;
          section_id: string | null;
          group_id: string | null;
          position: string;
          points_override: number | null;
          correct_override: unknown;
          created_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['online_exam_items']['Row']> & {
          workspace_id: string;
          online_exam_id: string;
          question_id: string;
          question_revision_id: string;
          position: string;
        };
        Update: Partial<Database['public']['Tables']['online_exam_items']['Row']>;
        Relationships: [];
      };
      exam_attempts: {
        Row: {
          id: string;
          workspace_id: string;
          online_exam_id: string;
          student_id: string | null;
          display_name: string | null;
          student_no: string | null;
          class_label: string | null;
          token_hash: string;
          started_at: Timestamp | null;
          deadline_at: Timestamp | null;
          submitted_at: Timestamp | null;
          status: 'in_progress' | 'submitted' | 'expired';
          ip_hash: string | null;
          ua_hash: string | null;
          flags: Record<string, unknown>;
          score: number | null;
          max_score: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['exam_attempts']['Row']> & {
          workspace_id: string;
          online_exam_id: string;
          token_hash: string;
        };
        Update: Partial<Database['public']['Tables']['exam_attempts']['Row']>;
        Relationships: [];
      };
      attempt_answers: {
        Row: {
          workspace_id: string;
          attempt_id: string;
          item_id: string;
          answer: unknown;
          is_correct: boolean | null;
          points: number | null;
          answered_at: Timestamp | null;
          time_spent_ms: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['attempt_answers']['Row']> & {
          workspace_id: string;
          attempt_id: string;
          item_id: string;
        };
        Update: Partial<Database['public']['Tables']['attempt_answers']['Row']>;
        Relationships: [];
      };
      omr_sessions: {
        Row: {
          id: string;
          workspace_id: string;
          test_id: string;
          class_id: string | null;
          status: 'pending' | 'scanning' | 'completed';
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['omr_sessions']['Row']> & {
          workspace_id: string;
          test_id: string;
        };
        Update: Partial<Database['public']['Tables']['omr_sessions']['Row']>;
        Relationships: [];
      };
      omr_scans: {
        Row: {
          id: string;
          workspace_id: string;
          session_id: string;
          asset_id: string | null;
          student_id: string | null;
          student_no_read: string | null;
          version_code: string | null;
          answers: Record<string, unknown>;
          confidence: Record<string, unknown>;
          needs_review: boolean;
          reviewed_by: string | null;
          score: number | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['omr_scans']['Row']> & {
          workspace_id: string;
          session_id: string;
        };
        Update: Partial<Database['public']['Tables']['omr_scans']['Row']>;
        Relationships: [];
      };
      report_card_summaries: {
        Row: {
          id: string;
          workspace_id: string;
          student_id: string;
          class_id: string;
          source_report: Record<string, unknown>;
          summary_text: string;
          status: 'draft' | 'approved';
          approved_by: string | null;
          approved_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['report_card_summaries']['Row']> & {
          workspace_id: string;
          student_id: string;
          class_id: string;
          source_report: Record<string, unknown>;
          summary_text: string;
        };
        Update: Partial<Database['public']['Tables']['report_card_summaries']['Row']>;
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          kind: string;
          payload: Record<string, unknown>;
          status: 'pending' | 'running' | 'succeeded' | 'failed';
          run_at: Timestamp;
          attempts: number;
          last_error: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['jobs']['Row']> & { kind: string };
        Update: Partial<Database['public']['Tables']['jobs']['Row']>;
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          workspace_id: string;
          actor_id: string | null;
          action: string;
          target_type: string | null;
          target_id: string | null;
          meta: Record<string, unknown>;
          created_at: Timestamp;
        };
        Insert: Partial<Database['public']['Tables']['audit_log']['Row']> & {
          workspace_id: string;
          action: string;
        };
        Update: Partial<Database['public']['Tables']['audit_log']['Row']>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      check_exam_rate_limit: {
        Args: { p_key: string; p_limit: number; p_window_sec: number };
        Returns: boolean;
      };
      get_entitlements: {
        Args: { p_ws: string };
        Returns: Record<string, unknown>;
      };
      increment_usage: {
        Args: { p_ws: string; p_metric: string; p_amount?: number };
        Returns: number;
      };
      is_member: {
        Args: { ws: string };
        Returns: boolean;
      };
      has_role: {
        Args: { ws: string; roles: string[] };
        Returns: boolean;
      };
      bulk_import_students: {
        Args: { p_workspace_id: string; p_class_id: string; p_rows: unknown };
        Returns: { inserted: number; linked: number };
      };
      bulk_delete_students: {
        Args: { p_workspace_id: string; p_student_ids: string[] };
        Returns: void;
      };
      link_attempts_to_students: {
        Args: { p_workspace_id: string; p_links: unknown };
        Returns: { linked: number };
      };
      approve_report_card_summary: {
        Args: { p_workspace_id: string; p_id: string };
        Returns: void;
      };
      get_class_report: {
        Args: { p_workspace_id: string; p_class_id: string };
        Returns: unknown;
      };
      get_outcome_report: {
        Args: { p_workspace_id: string; p_class_id: string; p_student_id?: string | null };
        Returns: unknown;
      };
      get_student_progress: {
        Args: { p_workspace_id: string; p_student_id: string };
        Returns: unknown;
      };
      get_weak_topics: {
        Args: { p_workspace_id: string; p_class_id: string };
        Returns: unknown;
      };
      apply_test_ops: {
        Args: { p_test_id: string; p_base_revision: number; p_ops: unknown };
        Returns: unknown;
      };
      spend_credits: {
        Args: {
          p_ws: string;
          p_amount: number;
          p_reason: string;
          p_ref_type?: string | null;
          p_ref_id?: string | null;
        };
        Returns: number;
      };
      refund_credits: {
        Args: {
          p_ws: string;
          p_amount: number;
          p_reason: string;
          p_ref_type?: string | null;
          p_ref_id?: string | null;
        };
        Returns: number;
      };
      create_ai_job: {
        Args: { p_ws: string; p_kind: string; p_input?: unknown };
        Returns: string;
      };
      complete_ai_job: {
        Args: {
          p_job_id: string;
          p_output: unknown;
          p_model: string;
          p_tokens_in: number;
          p_tokens_out: number;
          p_cost_micro: number;
          p_credits_charged: number;
        };
        Returns: null;
      };
      fail_ai_job: {
        Args: { p_job_id: string; p_error: string };
        Returns: null;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
